###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

enable_analytics: no
show_framelessgrid: no
show_lastmodified: yes