hide: true

fields:
  meta_title:
    display: Page Title
    type: text
    instructions: "Enter the page title to display in Google's search results (no more than 70 characters)."
  meta_desc:
    display: Page Description
    type: text
    instructions: "Enter a short description to display in Google's search results roughly 155 characters."

# These are the meta fields which enable you to add a meta title and description used by search engines.
